"""added view stats columns to card

Revision ID: 16021dd73d2c
Revises: b63c45dfc631
Create Date: 2016-12-23 06:35:05.925102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16021dd73d2c'
down_revision = 'b63c45dfc631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('correct_responses', sa.Integer(), nullable=True))
    op.add_column('card', sa.Column('total_views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'total_views')
    op.drop_column('card', 'correct_responses')
    # ### end Alembic commands ###
