"""changed Card name to title and added answer

Revision ID: 76fb7bf4762b
Revises: 16021dd73d2c
Create Date: 2017-01-23 14:07:14.665772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76fb7bf4762b'
down_revision = '16021dd73d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('answer', sa.String(length=100), nullable=True))
    op.add_column('card', sa.Column('title', sa.String(length=100), nullable=True))
    op.drop_column('card', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('card', 'title')
    op.drop_column('card', 'answer')
    # ### end Alembic commands ###
